# Generated by Django 2.2.13 on 2023-10-26 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierlabel', models.CharField(blank=True, max_length=100, null=True)),
                ('s_trace', models.CharField(blank=True, max_length=100, null=True)),
                ('s_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('s_id', models.CharField(blank=True, max_length=100, null=True)),
                ('s_name', models.CharField(blank=True, max_length=100, null=True)),
                ('wistronlabel', models.CharField(blank=True, max_length=100, null=True)),
                ('w_trace', models.CharField(blank=True, max_length=100, null=True)),
                ('w_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('w_id', models.CharField(blank=True, max_length=100, null=True)),
                ('w_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
                'ordering': ['-created'],
            },
        ),
    ]
